DekKMITL/DekKMITL/urls.py
from django.contrib import admin
from django.urls import path, include

from pages.views import home_view, about_view, rules_view, report_view
from account.views import register_view,login_view,logout_view,profile_view,profile_edit_view,profile_edit_password_view

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),

    path("",home_view,name='home_view'), 
    
    path("about/", about_view, name="about_view"),
    path("register/", register_view, name="register_view"),
    path("login/", login_view, name="login_view"),
    path("logout/", logout_view, name="logout_view"),
    path("profile/<int:user_id>", profile_view, name="profile_account_view"),
    path("profile/", profile_view, name="profile_view"),
    path("profile/edit",profile_edit_view,name="profile_edit_view"),
    path("profile/edit/password",profile_edit_password_view,name="profile_edit_password_view"),
    path("post/",include('post.urls')),
    path("account/",include('account.urls')),
    path("rules/",rules_view,name="rules_view"),
    path("reports/",report_view,name="report_view"),
    path("report",include('postreport.urls')),
    path("",include('pages.urls')),
]
if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

DekKMITL/post/urls.py
from django.urls import path
from . import views

app_name='post'
urlpatterns = [
    path('all-post/', views.all_post_view,name='all_post_view'),
    path('all-post/<str:status>', views.all_post_view,name='all_post_view'),
    path('details/<slug:post_slug>/', views.post_detail_view,name='details_view'),
    path('create/', views.post_create_view,name='create_view'),
    path('edit/<slug:post_slug>', views.post_edit_view,name='edit_view'),
    path('delete/<slug:post_slug>', views.post_delete_view,name='delete_view'),
    path('feed-page/',views.feed_page_view,name='feed_page_view'),
    path('your-feed/',views.following_feed_view,name='following_feed_view'),
    path('room/',views.room_list_view,name='room_list_view'),
    path('room/<str:room_name>',views.room_detail_view,name='room_detail_view'),
    path('like/<slug:slug>',views.like_view,name='like_view'),
    path('tag/',views.tag_view,name='tag_view'),
    path('tag/<str:tag>',views.tag_detail_view,name='tag_detail_view'),
    path('comment-like-toggle/<int:id>',views.comment_like_toggle_view,name='comment_like_toggle_view'),
    path('comment-delete/<int:id>',views.delete_comment_view,name='delete_comment_view'),
]
hx_patterns = [    
    path('room/hx/<str:room_name>/<str:status>',views.hx_room_detail,name='hx_room_detail'),
    path('tag/hx/<str:tag_name>/<str:status>',views.hx_tag_detail,name='hx_tag_detail'),
]
urlpatterns+= hx_patterns

DekKMITL/templates/components/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{%static '/css/base.css'%}">
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon/favicon.ico' %}" />
    <title>
        {% block site_title %} {% endblock %} | DekKMITL
    </title>

</head>

<body>
    {% include 'components/navbar.html' %}
    <div class="mainbg">{% block content %} {% endblock %}</div> {% include 'components/footer.html' %}
</body>
<link rel="stylesheet" href="{%static '/css/media_query.css'%}">

</html>

DekKMITL/templates/components/footer.html
{% load static%}
<footer class="redorange">
    <div class="footer-container vcenter">

        <!-- 1. logo -->
        <div class="logo footer-logo">
            <a href="/"><img src="{% static 'images/logotop.svg'%}" style="width:100%"></a>
        </div>

        <!-- 2. toolbar -->
        <div class="footer-content hcenter">
            <!-- 2.1 blog toolbar -->
            <div class="footer-toolbar">
                <div class="createblog vcenter footer-margin">
                    <div class="createblog-icon">
                        <a href="{%url 'post:create_view'%}" class="vcenter"><img src="{% static 'images/createblog.svg'%}" style="max-width:100%"></a>
                    </div>
                    <div class="createblog-text"><a href="{%url 'post:create_view'%}" class="footer-effect-shadow">ตั้งกระทู้</a></div>
                </div>
                <div class="chooseroom vcenter footer-margin">
                    <div class="chooseroom-icon">
                        <a href="{% url 'post:room_list_view' %}" class="vcenter"><img src="{% static 'images/room.svg'%}" style="max-width:100%"></a>
                    </div>
                    <div class="chooseroom-text"><a href="{% url 'post:room_list_view' %}" class="footer-effect-shadow">เลือกห้อง</a></div>
                </div>
                <div class="tag vcenter footer-margin">
                    <div class="tag-icon">
                        <a href="{%url 'post:tag_view'%}" class="vcenter"><img src="{% static 'images/hashtag.svg'%}" style="max-width:100%"></a>
                    </div>
                    <div class="tag-text"><a href="{%url 'post:tag_view'%}" class="footer-effect-shadow">แท็ก</a></div>
                </div>
            </div>
            <!-- 2.2 social -->
            <div class="social-container">
                <h3 class="social-title">SOCIAL</h3>
                <ul class="social">
                    <li><a href="#">Dek-KMITL</a></li>
                </ul>
            </div>
            <!-- 2.3 contact -->
            <div class="contactus-container">
                <h3 class="contactus-title">CONTACT US</h3>
                <ul class="contactus">
                    <li><a href="{%url 'report_view'%}">แจ้งปัญหา</a></li>
                    <li><a href="#">ติดต่อทีมงาน</a></li>
                </ul>
            </div>
        </div>

        <!-- 3. child pic -->
        <div class="footer-pic"><img src="{% static 'images/footerlogo.svg'%}" style="max-width:100%"></div>
    </div>
</footer>

DekKMITL/templates/components/navbar.html
{% load static%}
<nav class="redorange">
    <div class="navbar-container vcenter">
        <!-- 0. hide toolbar (media query) -->
        <div class="hide-navbar">
            <img src="{% static 'images/hidebar.svg'%}" onclick="toggleClass('toolbar_container','toolbar-show')" class="hide-toolbar" style="width:100%">
        </div>

        <!-- 1. logo -->
        <div class="logo vcenter">
            <a href="/"><img src="{% static 'images/logotop.svg'%}" class="logotop-pic"></a>
        </div>

        <!-- 2. toolbar -->
        <div class="toolbar-container vhcenter" id="toolbar_container">
            <div class="myfeed vhcenter effect-block">
                <div class="myfeed-icon">
                    <a href="/" class="vcenter toolbar-icon"><img src="{% static 'images/feed.svg'%}" style="width:100%"></a>
                </div>
                <div class="myfeed-text"><a href="/">หน้าหลัก</a></div>
            </div>
            <div class="createblog vhcenter effect-block">
                <div class="createblog-icon">
                    <a href="{%url 'post:create_view'%}" class="vcenter"><img src="{% static 'images/createblog.svg'%}" style="width:100%"></a>
                </div>
                <div class="createblog-text"><a href="{%url 'post:create_view'%}">ตั้งกระทู้</a></div>
            </div>
            <div class="chooseroom vhcenter effect-block">
                <div class="chooseroom-icon">
                    <a href="{% url 'post:room_list_view' %}" class="vcenter"><img src="{% static 'images/room.svg'%}" style="width:100%"></a>
                </div>
                <div class="chooseroom-text"><a href="{% url 'post:room_list_view' %}">เลือกห้อง</a></div>
            </div>
            <div class="tag vhcenter effect-block">
                <div class="tag-icon">
                    <a href="{%url 'post:tag_view'%}" class="vcenter"><img src="{% static 'images/hashtag.svg'%}" style="width:100%"></a>
                </div>
                <div class="tag-text"><a href="{%url 'post:tag_view'%}">แท็ก</a></div>
            </div>

            {% if request.user.is_admin %}

            <div class="tag vhcenter effect-block">
                <div class="tag-icon">
                    <a href="/admin" class="vcenter"><img src="{% static 'images/hashtag.svg'%}" style="width:100%"></a>
                </div>
                <div class="tag-text"><a href="/admin">Admin</a></div>
            </div>

            <div class="tag vhcenter effect-block">
                <div class="tag-icon">
                    <a href="{{request.user.get_absolute_url}}" class="vcenter"><img src="{% static 'images/hashtag.svg'%}" style="width:100%"></a>
                </div>
                <div class="tag-text"><a href="{{request.user.get_absolute_url}}">Profile</a></div>
            </div>

            {%endif%}

        </div>
        <!-- 3. search and login -->
        <div class="searchlogin-container vcenter">
            <!-- *3.1 already login -->
            {% if request.user.is_authenticated %}
            <div class="already-login-container" id="already_login" style="min-width:100%">
                <div class="user-profile-container vcenter" style="min-width:15%">
                    <div class="user-profile-navbar box-shadow-effect" onclick="toggleClass('profile_dropdown','profile-show')" style="background-image: url({{request.user.profile_image.url}})"></div>
                    <div class="profile-dropdown-content" id="profile_dropdown">
                        <div class="navbar-name">{{request.user.first_name|title}}&nbsp;{{request.user.last_name|title}}</div>
                        <a href="{%url 'profile_view'%}">หน้าโปรไฟล์ของคุณ</a>
                        <a href="{% url 'post:following_feed_view' %}">หน้าฟีดของคุณ</a>
                        <a href="{%url 'logout_view'%}">ออกจากระบบ</a>
                    </div>
                </div>
                <div class="chat-logo" style="width:32px">
                    <a href="#link to chat"><img src="{% static 'images/chatlogo.png'%}" class="chat-logo-pic brightness-effect"> </a>
                </div>
                <div class="notification-logo" style="width:32px">
                    <a href="#link to notification"><img src="{% static 'images/notification.png'%}" class="noti-logo-pic brightness-effect"> </a>
                </div>
            </div>

            {%else%}
            <!-- *3.1 not login -->
            <div class="login-frame vcenter" id="login_frame">
                <div class="login-text"><a href="{% url 'login_view' %}">เข้าสู่ระบบ ></a></div>
            </div>

            {% endif %}

            <!-- 3.2 search -->
            <div class="search-box">
                <button class="btn-search vhcenter brightness-effect"></button>
                <input type="text" id="mysearch" class="input-search" placeholder="ค้นหาบน Dek-KMITL">
            </div>
        </div>
    </div>
</nav>

<!-- javascript -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="{% static 'js/base.js'%}"></script>