DekKMITL/DekKMITL/urls.py
from django.contrib import admin
from django.urls import path, include

from pages.views import home_view, about_view, rules_view, report_view
from account.views import register_view,login_view,logout_view,profile_view,profile_edit_view,profile_edit_password_view

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),

    path("",home_view,name='home_view'), 
    
    path("about/", about_view, name="about_view"),
    path("register/", register_view, name="register_view"),
    path("login/", login_view, name="login_view"),
    path("logout/", logout_view, name="logout_view"),
    path("profile/<int:user_id>", profile_view, name="profile_account_view"),
    path("profile/", profile_view, name="profile_view"),
    path("profile/edit",profile_edit_view,name="profile_edit_view"),
    path("profile/edit/password",profile_edit_password_view,name="profile_edit_password_view"),
    path("post/",include('post.urls')),
    path("account/",include('account.urls')),
    path("rules/",rules_view,name="rules_view"),
    path("reports/",report_view,name="report_view"),
    path("report",include('postreport.urls')),
    path("",include('pages.urls')),
]
if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

DekKMITL/post/urls.py
from django.urls import path
from . import views

app_name='post'
urlpatterns = [
    path('all-post/', views.all_post_view,name='all_post_view'),
    path('all-post/<str:status>', views.all_post_view,name='all_post_view'),
    path('details/<slug:post_slug>/', views.post_detail_view,name='details_view'),
    path('create/', views.post_create_view,name='create_view'),
    path('edit/<slug:post_slug>', views.post_edit_view,name='edit_view'),
    path('delete/<slug:post_slug>', views.post_delete_view,name='delete_view'),
    path('feed-page/',views.feed_page_view,name='feed_page_view'),
    path('your-feed/',views.following_feed_view,name='following_feed_view'),
    path('room/',views.room_list_view,name='room_list_view'),
    path('room/<str:room_name>',views.room_detail_view,name='room_detail_view'),
    path('like/<slug:slug>',views.like_view,name='like_view'),
    path('tag/',views.tag_view,name='tag_view'),
    path('tag/<str:tag>',views.tag_detail_view,name='tag_detail_view'),
    path('comment-like-toggle/<int:id>',views.comment_like_toggle_view,name='comment_like_toggle_view'),
    path('comment-delete/<int:id>',views.delete_comment_view,name='delete_comment_view'),
]
hx_patterns = [    
    path('room/hx/<str:room_name>/<str:status>',views.hx_room_detail,name='hx_room_detail'),
    path('tag/hx/<str:tag_name>/<str:status>',views.hx_tag_detail,name='hx_tag_detail'),
]
urlpatterns+= hx_patterns

DekKMITL/templates/about.html
{% extends 'components/base.html' %}


{% block site_title %} 
About
{% endblock %}

{% block content%} 
This is about page.
{% endblock %}

DekKMITL/templates/home.html
{% extends 'components/base.html' %} {% load static%} {% block site_title%} Home {% endblock %} {% load humanize %} {% block content %}
<link rel="stylesheet" href="{%static '/css/home.css'%}">

<div class="home-container" style="max-width:1400px;margin:auto">

    <!-- 1.top3 and latest blog -->
    <div class="topblog-container">
        <!-- 1.1 top3 blog -->
        {% include 'pages/components/top3.html' %}
        <!-- 1.2 latest blog -->
        <div class="latest-blog-container" style="min-width:49%">
            <div class="home-title" style="border:0">กระทู้ล่าสุด</div>
            <div class="all-latest-blog" style="min-height:170px">
                <!-- ******************blog not found*****************8 -->
                {% if not latest_posts %}
                <div class="no-thumbnail-blog notfound-blog vhcenter">ยังไม่มีกระทู้ล่าสุด</div>
                {% else %}
                <!-- ********************loop blog*********************** -->
                {% for post in latest_posts %}
                <div class="no-thumbnail-blog vhcenter" onclick="window.location='{{post.get_absolute_url}}'">
                    <div class="user-profile-container profile-center vcenter" style="width:15%">
                        <a href="{{post.author.get_absolute_url}}">
                            <div class="user-profile-pic" style="background-image: url('{{post.author.get_profile_image_url}}')"></div>
                        </a>
                    </div>
                    <div class="blog-detail" style="width:85%">
                        <div class="blog-name wrap-name" style="max-width:100%">
                            <a href="{{post.get_absolute_url}}" class="blogfont">{{post.title}}</a>
                        </div>
                        <div class="blog-detail-2">
                            <div class="blog-username-date"><a href="{{post.author.get_absolute_url}}">{{post.author.first_name}} : {{post.date_created|naturaltime}}</a></div>
                            <div class="blog-like-comment vhcenter">
                                <img src="{% static 'images/like.png'%}" style="width:15px">{{post.liker.count}} &nbsp;
                                <img src="{% static 'images/comment.png'%}" style="width:15px">{{post.comments.all.count}}
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
                <!-- ************************************************* -->
                {% endif %}
            </div>
        </div>
    </div>

    <!-- 2. temporary blog -->
    <div class="homeblog-container">
        <div class="home-title">กระทู้ชั่วคราว</div>
        <div class="tempblog" style="min-height:150px">
            <!-- ******************blog not found*****************8 -->
            {% if not temporary_posts %}
            <div class="no-thumbnail-blog notfound-blog vhcenter">ยังไม่มีกระทู้</div>
            {% else %}
            <!-- ********************loop blog*********************** -->
            {% for post in temporary_posts %}
            <div class="no-thumbnail-blog vhcenter" onclick="window.location='{{post.get_absolute_url}}'">
                <div class="user-profile-container vcenter" style="width:15%">
                    <a href="{{post.author.get_absolute_url}}">
                        <div class="user-profile-pic" style="background-image: url('{{post.author.get_profile_image_url}}')"></div>
                    </a>
                </div>
                <div class="blog-detail" style="width:85%">
                    <div class="blog-name wrap-name" style="max-width:100%">
                        <a href="{{post.get_absolute_url}}" class="blogfont">{{post.title}}</a>
                    </div>
                    <div class="blog-detail-2">
                        <div class="blog-username-date"><a href="{{post.author.get_absolute_url}}">{{post.author.first_name}} : {{post.date_created|naturaltime}}</a></div>
                        <div class="blog-like-comment vhcenter">
                            <img src="{% static 'images/like.png'%}" style="width:15px">{{post.liker.count}} &nbsp;
                            <img src="{% static 'images/comment.png'%}" style="width:15px">{{post.comments.all.count}}
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            <!-- ************************************************* -->
            {% endif %}
        </div>
        <div class="see-all redorange vhcenter"><a href="{% url 'post:all_post_view' %}" class="see-all-text">ดูทั้งหมด ></a></div>
    </div>

    <!-- 3. poppular room -->
    <div class="homeblog-container">
        <div class="home-title">เลือกห้อง</div>
        <div class="all-poproom">
            <!-- ********************loop room*********************** -->
            {% for room in pop_rooms %}
            <div class="poproom">
                <div class="poproom-pic vhcenter">
                    <a href="{{room.get_absolute_url}}"><img src="{{room.get_icon_url}}" style="width:90px;height:90px"></a>
                </div>
                <div class="poproom-name vhcenter"><a href="{{room.get_absolute_url}}">{{room.verbose}}</a></div>
            </div>
            {% endfor %}
            <!-- ************************************************* -->
        </div>
        <div class="see-all redorange vhcenter"><a href="{% url 'post:room_list_view' %}" class="see-all-text">ดูทั้งหมด ></a></div>
    </div>

    <!-- 4. education info -->
    <div class="homeblog-container">
        <div class="home-title ">Update เรื่องเรียน</div>
        <div class="edublog ">
            <!-- ******************blog not found*****************8 -->
            {% if not room_educate_posts %}
            <div class="notfound-bigblog vhcenter">ยังไม่มีกระทู้</div>
            {% else %}
            <!-- ********************loop blog*********************** -->
            {% for post in room_educate_posts %}
            <div class="thumbnail-blog">
                <div class="blog-cover-container">
                    <a href="{{post.get_absolute_url}}">
                        <div class="blog-cover" style="background-image: url('{{post.get_cover_image_url}}')"></div>
                    </a>
                </div>
                <div class="blog-detail-container vhcenter">
                    <div class="user-profile-container vcenter" style="width:15%">
                        <a href="{{post.author.get_absolute_url}}">
                            <div class="user-profile-pic" style="background-image: url('{{post.author.get_profile_image_url}}');height:60px;width:60px"></div>
                        </a>
                    </div>
                    <div class="blog-detail" style="width:85%">
                        <div class=" two-line-wrap" style="max-width:100%">
                            <a href="{{post.get_absolute_url}}" class="blogfont">{{post.title}}</a>
                        </div>
                        <div class="blog-detail-2">
                            <div class="blog-username-date"><a href="{{post.author.get_absolute_url}}">{{post.author.first_name}} : {{post.date_created}}</a></div>
                            <div class="blog-like-comment vhcenter">
                                <img src="{% static 'images/like.png'%}" style="width:15px">{{post.liker.count}} &nbsp;
                                <img src="{% static 'images/comment.png'%}" style="width:15px">{{post.total_comments}}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            <!-- ************************************************* -->
            {% endif %}
        </div>
        <div class="see-all redorange vhcenter "><a href="{{room_educate.get_absolute_url}}" class="see-all-text">ดูทั้งหมด ></a>
        </div>
    </div>
</div>
<!-- back to top btn -->
<img src="{% static 'images/arrowup.png'%}" onclick="topFunction()" class="back-to-top" id="back_to_top"> {% endblock %}